x-common-vars:
  - &DOCKER_NETWORK ${DOCKER_NETWORK:-stacks}
  - &DOCKER_NETWORK_CIDR 10.0.0.0/24
  - &DOCKER_NETWORK_GATEWAY 10.0.0.1
  - &PROMETHEUS_IP 10.0.0.252
  - &CADVISOR_IP 10.0.0.253

name: monitoring

configs:
  # prometheus scraping config
  prometheus.yml:
    content: |
      # Global config
      global:
        external_labels:
          monitor: "hacknet"
      # A scrape configuration containing Prometheus and Docker
      scrape_configs:
      - job_name: cadvisor
        scrape_interval: 5s
        static_configs:
          - targets:
            - cadvisor:8080
        metric_relabel_configs:
          - source_labels: [ __name__ ]
            regex: '^(go_|cadvisor_version_info).+'
            action: drop
      - job_name: stacks
        scrape_interval: 5s
        static_configs:
          - targets:
            - stacks-miner-1:9153
            - stacks-miner-2:9153
            - stacks-miner-3:9153
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      default:
        ipv4_address: *PROMETHEUS_IP
    configs:
      - source: prometheus.yml
        target: /etc/prometheus/prometheus.yml
    depends_on:
      - cadvisor
    ports:
      - '0.0.0.0:${PROM_HTTP:-9090}:${PROM_HTTP:-9090}'
    command:
      - --config.file=/etc/prometheus/prometheus.yml
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    networks:
      default:
        ipv4_address: *CADVISOR_IP
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - '0.0.0.0:8080:8080'
    command: "--enable_metrics=cpu,cpuLoad,disk,diskIO,memory"

networks:
  default:
    name: *DOCKER_NETWORK
    ipam:
      driver: default
      config:
        - subnet: *DOCKER_NETWORK_CIDR
          gateway: *DOCKER_NETWORK_GATEWAY
