[node]
name = "miner"
rpc_bind = "0.0.0.0:20443"
p2p_bind = "0.0.0.0:20444"
data_url = "http://127.0.0.1:20443"
p2p_address = "127.0.0.1:20443"
#working_dir = "$DATA_DIR"
working_dir = "/data"
bootstrap_node = "$BOOTSTRAP_NODE"

seed = "$MINER_SEED"
local_peer_seed = "$MINER_SEED"

miner = true
stacker = true
use_test_genesis_chainstate = true
pox_sync_sample_secs = 0
wait_time_for_blocks = 0
wait_time_for_microblocks = 0
mine_microblocks = false
microblock_frequency = 1000
# stacker_dbs = [
#     "ST000000000000000000002AMW42H.signers-0-8",
#     "ST000000000000000000002AMW42H.signers-1-5",
#     "ST000000000000000000002AMW42H.signers-0-11",
#     "ST000000000000000000002AMW42H.miners",
#     "ST000000000000000000002AMW42H.signers-1-1",
#     "ST000000000000000000002AMW42H.signers-0-4",
#     "ST000000000000000000002AMW42H.signers-1-4",
#     "ST000000000000000000002AMW42H.signers-1-0",
#     "ST000000000000000000002AMW42H.signers-0-6",
#     "ST000000000000000000002AMW42H.signers-1-6",
#     "ST000000000000000000002AMW42H.signers-1-2",
#     "ST000000000000000000002AMW42H.signers-0-0",
#     "ST000000000000000000002AMW42H.signers-0-2",
#     "ST000000000000000000002AMW42H.signers-1-9",
#     "ST000000000000000000002AMW42H.signers-1-10",
#     "ST000000000000000000002AMW42H.signers-0-7",
#     "ST000000000000000000002AMW42H.signers-0-1",
#     "ST000000000000000000002AMW42H.signers-1-8",
#     "ST000000000000000000002AMW42H.signers-0-10",
#     "ST000000000000000000002AMW42H.signers-1-12",
#     "ST000000000000000000002AMW42H.signers-0-5",
#     "ST000000000000000000002AMW42H.signers-0-3",
#     "ST000000000000000000002AMW42H.signers-1-3",
#     "ST000000000000000000002AMW42H.signers-1-11",
#     "ST000000000000000000002AMW42H.signers-0-9",
#     "ST000000000000000000002AMW42H.signers-0-12",
#     "ST000000000000000000002AMW42H.signers-1-7"
#   ]

[miner]
first_attempt_time_ms = 180_000
subsequent_attempt_time_ms = 360_000
microblock_attempt_time_ms = 10
mining_key = "$MINER_SEED"
block_reward_recipient = "$REWARD_RECIPIENT"

[connection_options]
auth_token = "12345"
private_neighbors = true

[burnchain]
chain = "bitcoin"
mode = "nakamoto-neon"
poll_time_secs = 1
magic_bytes = "T3"
pox_prepare_length = $POX_PREPARE_LENGTH
pox_reward_length = $POX_REWARD_LENGTH
burn_fee_cap = 20_000

### bitcoind-regtest connection info
peer_host = "$BITCOIN_PEER_HOST"
peer_port = $BITCOIN_PEER_PORT
rpc_port = $BITCOIN_RPC_PORT
rpc_ssl = false
username = "$BITCOIN_RPC_USER"
password = "$BITCOIN_RPC_PASS"
timeout = 30
wallet_name = "$BITCOIN_WALLET"

[[burnchain.epochs]]
epoch_name = "1.0"
start_height = 0

[[burnchain.epochs]]
epoch_name = "2.0"
start_height = $STACKS_20_HEIGHT

[[burnchain.epochs]]
epoch_name = "2.05"
start_height = $STACKS_2_05_HEIGHT

[[burnchain.epochs]]
epoch_name = "2.1"
start_height = $STACKS_21_HEIGHT

[[burnchain.epochs]]
epoch_name = "2.2"
start_height = $STACKS_22_HEIGHT

[[burnchain.epochs]]
epoch_name = "2.3"
start_height = $STACKS_23_HEIGHT

[[burnchain.epochs]]
epoch_name = "2.4"
start_height = $STACKS_24_HEIGHT

[[burnchain.epochs]]
epoch_name = "2.5"
start_height = $STACKS_25_HEIGHT

[[burnchain.epochs]]
epoch_name = "3.0"
start_height = $STACKS_30_HEIGHT

[[burnchain.epochs]]
epoch_name = "3.1"
start_height = $STACKS_31_HEIGHT

[[ustx_balance]]
address = "ST2SBXRBJJTH7GV5J93HJ62W2NRRQ46XYBK92Y039" # sBTC deployer
amount = 10000000000000000

[[ustx_balance]]
address = "ST24VB7FBXCBV6P0SRDSPSW0Y2J9XHDXNHW9Q8S7H" # sBTC signer 1
amount = 10000000000000000

[[ustx_balance]]
address = "ST2XAK68AR2TKBQBFNYSK9KN2AY9CVA91A7CSK63Z" # sBTC signer 2
amount = 10000000000000000

[[ustx_balance]]
address = "ST1J9R0VMA5GQTW65QVHW1KVSKD7MCGT27X37A551" # sBTC signer 3
amount = 10000000000000000


[[ustx_balance]]
address = "ST1YEHRRYJ4GF9CYBFFN0ZVCXX1APSBEEQ5KEDN7M" # Stacker 1 (Alice)
amount = 10000000000000000

[[ustx_balance]]
address = "ST1WNJTS9JM1JYGK758B10DBAMBZ0K23ADP392SBV" # Stacker 2 (Bobe)
amount = 10000000000000000

[[ustx_balance]]
address = "ST1MDWBDVDGAANEH9001HGXQA6XRNK7PX7A7X8M6R" # Stacker 3 (Charlie)
amount = 10000000000000000

[[ustx_balance]]
# This is a 2-3 multi-sig address controlled using the above three
# addresses. The above three accounts are also in the
# `docker/sbtc/signer/README.md` file, and the resulting multi-sig address
# below was created using the SignerWallet struct.
address = "SN3R84XZYA63QS28932XQF3G1J8R9PC3W76P9CSQS"
amount = 10000000000000000

[[ustx_balance]]
address = "ST3497E9JFQ7KB9VEHAZRWYKF3296WQZEXBPXG193" # Demo principal
amount = 10000000000000000
