name: Lint Docker Compose

on:
  pull_request:
  workflow_dispatch:

jobs:
  dclint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: docker-compose-linter/dclint-github-action@v3.1.0
        with:
          path: ./docker/docker-compose.yml
          recursive: true
